### ISSUE TITLE
HookToken and SpreadToken

### ISSUE THREAD

**Issue by mikelpr** [tweag/inline-js#84]
**Describe the bug**
I can't use ?? with the [js||] quasiquoter

**To Reproduce**
t1 `_:: ByteString <- eval jsesh [js|return null ?? "hi"|]`
t2 `_ <- eval jsesh [js|return {...{}}|]`
t1 won't compile with error `HookToken {tokenSpan = TokenPn 13 1 14, tokenComment = []}`
t2 won't compile with error `SpreadToken {tokenSpan = TokenPn 8 1 9, tokenComment = []}`

**Expected behavior**
both supported

**Environment**
 - OS name + version: Fedora 34, nix
 - Version of the code: 71c2906e046058af33b80407e5897b36aceebba7

**Additional context**
funny thing is, searching for these in the repo, github doesn't find references to any of them

**Comment by TerrorJack** [comment]
`inline-js` uses `language-javascript` to parse JS code, and `language-javascript` doesn't support the nullish coalescing operator. In the future we may switch away from `language-javascript` in favor of a more battle-tested JS parser to address this kind of problem.
